"""
Feature Taxonomy — Phase 13.7.GB

Defines capability features for the groupby_regression subproject.
Each feature maps to its associated tests (proof) and benchmark checks (bench_proof).
The test layer classification in test_layer_classification.py determines
whether a feature is Verified or Smoke-only.

Phase 13.7.GB — v02 proposal §2.1, §4.3
"""

# fmt: off

FEATURE_TAXONOMY = {
    # ====== KERNEL — Low-level regression kernels ======
    "KERNEL.single_fit": {
        "name": "Single-target OLS kernel",
        "description": "Core Numba-accelerated single-target ordinary least squares kernel",
        "module": "groupby_regression_kernels",
        "proof": [
            "test_groupby_regression_kernels.py::TestSingleFitCorrectness::test_basic_fit",
            "test_groupby_regression_kernels.py::TestSingleFitCorrectness::test_weighted_fit",
            "test_groupby_regression_kernels.py::TestSingleFitCorrectness::test_insufficient_data",
        ],
        "bench_proof": ["bench_groupby_regression_kernels.py::validate_correctness() [GATED]"],
        "impl_tag": "NUMBA",
    },
    "KERNEL.multi_fit": {
        "name": "Multi-target OLS kernel",
        "description": "Numba-accelerated multi-target regression",
        "module": "groupby_regression_kernels",
        "proof": ["test_groupby_regression_kernels.py::TestMultiFitCorrectness::test_multi_target_fit"],
        "bench_proof": ["bench_groupby_regression_kernels.py::validate_correctness() [GATED]"],
        "impl_tag": "NUMBA",
    },
    "KERNEL.nan_handling": {
        "name": "NaN detection and filtering in kernels",
        "description": "Kernels detect and filter NaN values before regression",
        "module": "groupby_regression_kernels",
        "proof": [
            "test_groupby_regression_kernels.py::TestSingleFitCorrectness::test_nan_detection",
            "test_groupby_regression_kernels.py::TestSingleFitCorrectness::test_nan_filtering",
        ],
        "bench_proof": [],
        "impl_tag": "NUMBA",
    },
    "KERNEL.status_codes": {
        "name": "Status code encoding/decoding",
        "description": "Bitfield status codes for fit quality",
        "module": "groupby_regression_kernels",
        "proof": [
            "test_groupby_regression_kernels.py::TestStatusCode::test_decode_ok",
            "test_groupby_regression_kernels.py::TestStatusCode::test_decode_single_bits",
            "test_groupby_regression_kernels.py::TestStatusCode::test_decode_combined_bits",
            "test_groupby_regression_kernels.py::TestStatusCode::test_decode_vectorized",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "KERNEL.single_multi_parity": {
        "name": "Single-fit vs multi-fit kernel parity",
        "description": "Single-target and multi-target kernels produce identical results",
        "module": "groupby_regression_kernels",
        "proof": ["test_groupby_regression_kernels.py::TestKernelParity::test_single_vs_multi_parity"],
        "bench_proof": ["bench_groupby_regression_kernels.py::Numba/NumPy parity [GATED]"],
        "impl_tag": "NUMBA",
    },
    "KERNEL.numba_numpy_parity": {
        "name": "Numba vs NumPy backend parity",
        "description": "Numba JIT and NumPy reference produce identical results",
        "module": "groupby_regression_kernels",
        "proof": [
            "test_groupby_regression_kernels.py::TestNumbaNumpyParity::test_numba_numpy_exact_parity",
            "test_groupby_regression_kernels.py::TestNumbaNumpyParity::test_numba_numpy_parity_with_noise",
        ],
        "bench_proof": ["bench_groupby_regression_kernels.py::Numba/NumPy parity [GATED]"],
        "impl_tag": "NUMBA",
    },
    "KERNEL.mc_validation": {
        "name": "Monte Carlo ground-truth validation",
        "description": "Kernel output validated against analytically known MC coefficients",
        "module": "groupby_regression_kernels",
        "proof": [
            "test_groupby_regression_kernels.py::TestMCValidation::test_single_fit_mc_validation_no_noise",
            "test_groupby_regression_kernels.py::TestMCValidation::test_single_fit_mc_validation_with_noise",
            "test_groupby_regression_kernels.py::TestMCValidation::test_multi_fit_mc_validation_no_noise",
            "test_groupby_regression_kernels.py::TestMCValidation::test_mc_validation_varying_features",
        ],
        "bench_proof": ["bench_groupby_regression_kernels.py::validate_correctness() [GATED]"],
        "impl_tag": "NUMBA",
    },
    "KERNEL.dispatch": {
        "name": "Kernel dispatch logic",
        "description": "Correct kernel selected based on target count and filter mode",
        "module": "groupby_regression_kernels",
        "proof": [
            "test_groupby_regression_kernels.py::TestKernelDispatch::test_single_target_uses_single_kernel",
            "test_groupby_regression_kernels.py::TestKernelDispatch::test_multi_target_uses_multi_kernel",
            "test_groupby_regression_kernels.py::TestKernelDispatch::test_filter_mode_uses_single_kernel",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "KERNEL.large_scale": {
        "name": "Large-scale correctness (50k+ groups)",
        "description": "Kernel correctness maintained at production scale",
        "module": "groupby_regression_kernels",
        "proof": [
            "test_groupby_regression_kernels.py::TestLargeScale::test_large_scale_correctness_50k_groups",
            "test_groupby_regression_kernels.py::TestLargeScale::test_large_scale_multi_target",
        ],
        "bench_proof": ["bench_groupby_regression_kernels.py::validate_correctness() [GATED]"],
        "impl_tag": "NUMBA",
    },
    "KERNEL.streaming_memory": {
        "name": "Streaming RSS stability",
        "description": "Memory stays bounded during streaming chunk-loop processing",
        "module": "groupby_regression_kernels",
        "proof": [
            "test_groupby_regression_kernels.py::TestStreaming::test_streaming_chunk_loop_rss_stability",
            "test_groupby_regression_kernels.py::TestStreaming::test_streaming_multifit_rss_stability",
        ],
        "bench_proof": [
            "bench_groupby_regression_memory.py::RSS drift < 5% [GATED]",
            "bench_groupby_regression_memory.py::RSS CV < 0.1 [GATED]",
        ],
        "impl_tag": "NUMBA",
    },
    "KERNEL.numba_speedup": {
        "name": "Numba performance ratios",
        "description": "Numba achieves target speedup over NumPy reference",
        "module": "groupby_regression_kernels",
        "proof": [
            "test_groupby_regression_kernels.py::TestPerformance::test_numba_vs_numpy_ratio",
            "test_groupby_regression_kernels.py::TestPerformance::test_multifit_speedup",
        ],
        "bench_proof": [],
        "impl_tag": "NUMBA",
    },
    "KERNEL.jit_signatures": {
        "name": "JIT compilation signatures",
        "description": "Numba JIT signatures compile correctly",
        "module": "groupby_regression_kernels",
        "proof": [
            "test_groupby_regression_kernels.py::TestJITSignatures::test_single_fit_jit_signatures",
            "test_groupby_regression_kernels.py::TestJITSignatures::test_multi_fit_jit_signatures",
        ],
        "bench_proof": [],
        "impl_tag": "NUMBA",
    },

    # ====== GROUPBY.ROBUST — Robust regression ======
    "GROUPBY.ols_basic": {
        "name": "OLS basic fit (make_linear_fit)",
        "description": "Basic ordinary least squares group-wise regression",
        "module": "groupby_regression",
        "proof": ["test_groupby_regression.py::test_make_linear_fit_basic"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "GROUPBY.robust_basic": {
        "name": "Robust fit (make_parallel_fit)",
        "description": "HuberRegressor-based robust group-wise regression",
        "module": "groupby_regression",
        "proof": [
            "test_groupby_regression.py::test_make_parallel_fit_robust",
            "test_groupby_regression.py::test_make_parallel_fit_robust_v2",
        ],
        "bench_proof": ["bench_comparison.py::compute_agreement() [MONITOR]"],
        "impl_tag": "STATSMODELS",
    },
    "GROUPBY.prediction": {
        "name": "Prediction output",
        "description": "addPrediction flag adds predicted values to output",
        "module": "groupby_regression",
        "proof": ["test_groupby_regression.py::test_prediction_accuracy"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "GROUPBY.missing_values": {
        "name": "Missing value handling",
        "description": "NaN/inf values handled gracefully in group-wise fits",
        "module": "groupby_regression",
        "proof": ["test_groupby_regression.py::test_missing_values"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "GROUPBY.exact_recovery": {
        "name": "Exact coefficient recovery (robust)",
        "description": "Robust fitter recovers exact coefficients on noiseless data",
        "module": "groupby_regression",
        "proof": [
            "test_groupby_regression.py::test_exact_coefficient_recovery",
            "test_groupby_regression.py::test_exact_coefficient_recovery_parallel",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "GROUPBY.outlier_resilience": {
        "name": "Robust outlier resilience",
        "description": "HuberRegressor resists outlier contamination",
        "module": "groupby_regression",
        "proof": ["test_groupby_regression.py::test_robust_outlier_resilience"],
        "bench_proof": [],
        "impl_tag": "STATSMODELS",
    },
    "GROUPBY.cast_dtype": {
        "name": "Output dtype casting",
        "description": "Fit results cast to specified dtype",
        "module": "groupby_regression",
        "proof": ["test_groupby_regression.py::test_cast_dtype_effect"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "GROUPBY.min_stat": {
        "name": "Minimum statistics per predictor",
        "description": "Groups below min_stat excluded from fitting",
        "module": "groupby_regression",
        "proof": [
            "test_groupby_regression.py::test_min_stat_per_predictor",
            "test_groupby_regression.py::test_insufficient_data",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "GROUPBY.sigma_cut": {
        "name": "Sigma cut outlier rejection",
        "description": "MAD-based sigma cut for iterative outlier removal",
        "module": "groupby_regression",
        "proof": ["test_groupby_regression.py::test_sigma_cut_impact"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "GROUPBY.custom_fitter": {
        "name": "Custom fitter support",
        "description": "User-supplied fitting function via fitter parameter",
        "module": "groupby_regression",
        "proof": ["test_groupby_regression.py::test_make_parallel_fit_with_custom_fitter"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "GROUPBY.linear_fitter": {
        "name": "LinearRegression fitter",
        "description": "sklearn LinearRegression as alternative fitter",
        "module": "groupby_regression",
        "proof": ["test_groupby_regression.py::test_make_parallel_fit_with_linear_regression"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "GROUPBY.diagnostics": {
        "name": "Diagnostic columns (robust)",
        "description": "RMS, MAD, bin_count diagnostic columns",
        "module": "groupby_regression",
        "proof": ["test_groupby_regression.py::test_diagnostics_columns_present"],
        "bench_proof": [],
        "impl_tag": None,
    },

    # ====== GROUPBY.OPT — Optimized v2/v3/v4 ======
    "GROUPBY.v2_basic": {
        "name": "V2 optimized implementation",
        "description": "V2 groupby regression with batch processing",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_groupby_regression_optimized.py::test_basic_fit_serial",
            "test_groupby_regression_optimized.py::test_basic_fit_parallel",
            "test_groupby_regression_optimized.py::test_v2_group_rows_not_multiplied_by_targets",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "GROUPBY.v3_basic": {
        "name": "V3 optimized implementation",
        "description": "V3 with intercept control, diagnostics, weighted fits",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_groupby_regression_optimized.py::test_v3_fit_intercept_true",
            "test_groupby_regression_optimized.py::test_v3_fit_intercept_false",
            "test_groupby_regression_optimized.py::test_v3_parameter_errors",
            "test_groupby_regression_optimized.py::test_v3_inf_nan_filtering",
            "test_groupby_regression_optimized.py::test_v3_multiple_predictors",
            "test_groupby_regression_optimized.py::test_v3_diagnostics_control",
            "test_groupby_regression_optimized.py::test_v3_weighted_fits",
            "test_groupby_regression_optimized.py::test_v3_singular_matrix_handling",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "GROUPBY.v4_basic": {
        "name": "V4 optimized implementation",
        "description": "V4 with Numba backend, fast path, multi-column grouping",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_groupby_regression_optimized.py::test_v4_fit_intercept_true",
            "test_groupby_regression_optimized.py::test_v4_fit_intercept_false",
            "test_groupby_regression_optimized.py::test_v4_parameter_errors",
            "test_groupby_regression_optimized.py::test_v4_inf_nan_filtering",
            "test_groupby_regression_optimized.py::test_v4_multiple_predictors",
            "test_groupby_regression_optimized.py::test_v4_diagnostics_control",
            "test_groupby_regression_optimized.py::test_v4_weighted_fits",
            "test_groupby_regression_optimized.py::test_v4_singular_matrix_handling",
        ],
        "bench_proof": [],
        "impl_tag": "NUMBA",
    },
    "GROUPBY.opt_prediction": {
        "name": "Prediction accuracy (optimized)",
        "description": "Optimized implementations produce correct predictions",
        "module": "groupby_regression_optimized",
        "proof": ["test_groupby_regression_optimized.py::test_prediction_accuracy"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "GROUPBY.opt_missing": {
        "name": "Missing values (optimized)",
        "description": "NaN handling in optimized implementations",
        "module": "groupby_regression_optimized",
        "proof": ["test_groupby_regression_optimized.py::test_missing_values"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "GROUPBY.opt_recovery": {
        "name": "Coefficient recovery (optimized)",
        "description": "Optimized fit recovers exact coefficients",
        "module": "groupby_regression_optimized",
        "proof": ["test_groupby_regression_optimized.py::test_exact_coefficient_recovery"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "GROUPBY.opt_outlier": {
        "name": "Outlier resilience (optimized)",
        "description": "Optimized robust implementation handles outliers",
        "module": "groupby_regression_optimized",
        "proof": ["test_groupby_regression_optimized.py::test_robust_outlier_resilience"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "GROUPBY.batch_strategy": {
        "name": "Batch strategy selection",
        "description": "Auto-selection of batch processing strategy",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_groupby_regression_optimized.py::test_batch_strategy_auto",
            "test_groupby_regression_optimized.py::test_batch_strategy_size_bucketing",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "GROUPBY.opt_multi_target": {
        "name": "Multiple targets (optimized)",
        "description": "Optimized implementations support multiple fit targets",
        "module": "groupby_regression_optimized",
        "proof": ["test_groupby_regression_optimized.py::test_multiple_targets"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "GROUPBY.opt_precision": {
        "name": "Statistical precision (optimized)",
        "description": "Float precision and dtype casting in optimized path",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_groupby_regression_optimized.py::test_statistical_precision",
            "test_groupby_regression_optimized.py::test_cast_dtype",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "GROUPBY.opt_edge_cases": {
        "name": "Edge cases (optimized)",
        "description": "Single group, empty selection, insufficient data",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_groupby_regression_optimized.py::test_insufficient_data",
            "test_groupby_regression_optimized.py::test_single_group",
            "test_groupby_regression_optimized.py::test_empty_after_selection",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "GROUPBY.v3_v4_parity": {
        "name": "V3/V4 numerical parity",
        "description": "V3 and V4 produce identical numerical results",
        "module": "groupby_regression_optimized",
        "proof": ["test_groupby_regression_optimized.py::test_v3_v4_parity"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "GROUPBY.threading_backend": {
        "name": "Threading backend consistency",
        "description": "Loky and threading backends produce identical results",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_groupby_regression_optimized.py::test_threading_backend_small_groups",
            "test_groupby_regression_optimized.py::test_threading_backend_tiny_groups",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "GROUPBY.fast_backend": {
        "name": "Fast backend consistency",
        "description": "V4 fast path matches standard path numerically",
        "module": "groupby_regression_optimized",
        "proof": ["test_groupby_regression_optimized.py::test_fast_backend_consistency"],
        "bench_proof": [],
        "impl_tag": "NUMBA",
    },
    "GROUPBY.numba_backend": {
        "name": "Numba backend consistency",
        "description": "Numba backend matches standard implementation",
        "module": "groupby_regression_optimized",
        "proof": ["test_groupby_regression_optimized.py::test_numba_backend_consistency"],
        "bench_proof": [],
        "impl_tag": "NUMBA",
    },
    "GROUPBY.multi_col_parity": {
        "name": "Multi-column groupby V4/V2 parity",
        "description": "V4 multi-column grouping matches V2 reference",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_groupby_regression_optimized.py::test_numba_multicol_groupby_v4_matches_v2",
            "test_groupby_regression_optimized.py::test_numba_multicol_weighted_v4_matches_v2",
        ],
        "bench_proof": [],
        "impl_tag": "NUMBA",
    },
    "GROUPBY.opt_diagnostics": {
        "name": "Diagnostics (optimized)",
        "description": "Numba diagnostic output in V4",
        "module": "groupby_regression_optimized",
        "proof": ["test_groupby_regression_optimized.py::test_numba_diagnostics_v4"],
        "bench_proof": [],
        "impl_tag": "NUMBA",
    },
    "GROUPBY.v2_v3_v4_groups": {
        "name": "V2/V3/V4 structural group consistency",
        "description": "All optimized versions produce consistent group structure",
        "module": "groupby_regression_optimized",
        "proof": ["test_groupby_regression_optimized.py::test_v2_v3_v4_identical_groups_3col"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "GROUPBY.parallel_speedup": {
        "name": "Parallel speedup (optimized)",
        "description": "Parallel execution achieves speedup over serial",
        "module": "groupby_regression_optimized",
        "proof": ["test_groupby_regression_optimized.py::test_parallel_speedup"],
        "bench_proof": [],
        "impl_tag": None,
    },

    # ====== V5 — Batch API ======
    "V5.basic": {
        "name": "V5 batch API basic",
        "description": "V5 batch API returns correct DataFrame",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_phase_12_8_gb.py::TestV5BasicFunctionality::test_single_fit_returns_dataframe",
            "test_phase_12_8_gb.py::TestV5BasicFunctionality::test_multiple_fits_same_target",
            "test_phase_12_8_gb.py::TestV5BasicFunctionality::test_different_targets",
            "test_phase_12_8_gb.py::TestV5BasicFunctionality::test_different_weights_per_fit",
            "test_phase_12_8_gb.py::TestV5BasicFunctionality::test_different_linear_columns_per_fit",
            "test_phase_12_8_gb.py::TestV5BasicFunctionality::test_no_intercept",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "V5.v4_parity": {
        "name": "V5/V4 numerical parity",
        "description": "V5 batch API reproduces V4 results exactly",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_phase_12_8_gb.py::TestV5V4Parity::test_single_fit_matches_v4",
            "test_phase_12_8_gb.py::TestV5V4Parity::test_multiple_fits_match_v4_merged",
            "test_phase_12_8_gb.py::TestV5V4Parity::test_precision_float32_input",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "V5.chunk_invariance": {
        "name": "V5 chunk-size independence",
        "description": "Different chunk sizes produce identical results",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_phase_12_8_gb.py::TestV5ChunkInvariance::test_chunks_1_vs_4_identical",
            "test_phase_12_8_gb.py::TestV5ChunkInvariance::test_chunks_1_vs_8_identical",
            "test_phase_12_8_gb.py::TestV5ChunkInvariance::test_chunk_boundaries_never_split_groups",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "V5.validation": {
        "name": "V5 input validation",
        "description": "V5 raises appropriate errors for invalid inputs",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_phase_12_8_gb.py::TestV5ErrorHandling::test_shared_suffix_duplicate_targets_raises",
            "test_phase_12_8_gb.py::TestV5ErrorHandling::test_duplicate_output_columns_raises",
            "test_phase_12_8_gb.py::TestV5ErrorHandling::test_mismatched_lengths_raises",
            "test_phase_12_8_gb.py::TestV5ErrorHandling::test_empty_fit_columns_raises",
            "test_phase_12_8_gb.py::TestV5ErrorHandling::test_missing_columns_raises",
            "test_phase_12_8_gb.py::TestV5ErrorHandling::test_null_in_gb_columns_raises",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "V5.edge_cases": {
        "name": "V5 edge cases",
        "description": "Empty DataFrame, single group, insufficient data, selection",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_phase_12_8_gb.py::TestV5EdgeCases::test_empty_dataframe",
            "test_phase_12_8_gb.py::TestV5EdgeCases::test_single_group",
            "test_phase_12_8_gb.py::TestV5EdgeCases::test_insufficient_data_group",
            "test_phase_12_8_gb.py::TestV5EdgeCases::test_selection_parameter",
            "test_phase_12_8_gb.py::TestV5Diagnostics::test_compute_mad_false",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "V5.diagnostics": {
        "name": "V5 diagnostic output",
        "description": "V5 diagnostic columns, per-fit diagnostics, n_total",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_phase_12_8_gb.py::TestV5Diagnostics::test_diag_true_adds_columns",
            "test_phase_12_8_gb.py::TestV5Diagnostics::test_per_fit_diagnostics",
            "test_phase_12_8_gb.py::TestV5Diagnostics::test_diag_n_total_correct",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "V5.metadata": {
        "name": "V5 metadata generation",
        "description": "V5 generates metadata with schema, formulas, parameters",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_phase_12_8_gb.py::TestV5Diagnostics::test_return_metadata",
            "test_phase_12_8_gb.py::TestV5Diagnostics::test_metadata_structure",
            "test_phase_12_8_gb.py::TestV5Diagnostics::test_metadata_formulas",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "V5.sort_helpers": {
        "name": "V5 internal sort helpers",
        "description": "Multi-key sort and group boundary detection",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_phase_12_8_gb.py::TestV5InternalHelpers::test_sort_indices_single_key",
            "test_phase_12_8_gb.py::TestV5InternalHelpers::test_sort_indices_multi_key",
            "test_phase_12_8_gb.py::TestV5InternalHelpers::test_group_boundaries_correct",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "V5.performance": {
        "name": "V5 performance vs V4",
        "description": "V5 batch API faster than equivalent V4 sequential calls",
        "module": "groupby_regression_optimized",
        "proof": ["test_phase_12_8_gb.py::TestV5Performance::test_v5_faster_than_v4_multiple"],
        "bench_proof": ["bench_v5.py::timing [MONITOR]"],
        "impl_tag": None,
    },
    "V5.numba_parity": {
        "name": "V5 Numba matches sequential",
        "description": "V5 Numba parallel backend reproduces sequential results",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_phase_12_9_gb.py::TestV5NumbaParallel::test_single_fit_matches",
            "test_phase_12_9_gb.py::TestV5NumbaParallel::test_multi_fit_matches",
            "test_phase_12_9_gb.py::TestV5NumbaParallel::test_unweighted_matches",
            "test_phase_12_9_gb.py::TestV5NumbaParallel::test_no_intercept_matches",
        ],
        "bench_proof": [],
        "impl_tag": "NUMBA",
    },
    "V5.backend_selection": {
        "name": "V5 backend auto-selection",
        "description": "Automatic backend selection based on availability",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_phase_12_9_gb.py::TestBackendSelection::test_select_backend_sequential",
            "test_phase_12_9_gb.py::TestBackendSelection::test_select_backend_numba",
            "test_phase_12_9_gb.py::TestBackendSelection::test_select_backend_numba_unavailable",
            "test_phase_12_9_gb.py::TestBackendSelection::test_select_backend_auto_numba",
            "test_phase_12_9_gb.py::TestBackendSelection::test_select_backend_auto_sequential",
            "test_phase_12_9_gb.py::TestBackendSelection::test_select_backend_auto_no_numba",
        ],
        "bench_proof": [],
        "impl_tag": "NUMBA",
    },
    "V5.status_codes": {
        "name": "V5 status codes",
        "description": "V5 output includes per-group status codes",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_phase_12_9_gb.py::TestV5Diagnostics::test_status_code_constants",
            "test_phase_12_9_gb.py::TestV5Diagnostics::test_status_to_string_mapping",
            "test_phase_12_9_gb.py::TestV5Diagnostics::test_status_codes_in_output",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "V5.per_fit_diag": {
        "name": "V5 per-fit diagnostics",
        "description": "Per-fit n_valid with NaN handling, shared n_total",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_phase_12_9_gb.py::TestV5Diagnostics::test_per_fit_n_valid_different_nans",
            "test_phase_12_9_gb.py::TestV5Diagnostics::test_shared_n_total_only",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "V5.parallel_edge": {
        "name": "V5 parallel edge cases",
        "description": "n_jobs > groups, single group, insufficient data",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_phase_12_9_gb.py::TestV5Parallel::test_n_jobs_greater_than_groups",
            "test_phase_12_9_gb.py::TestV5Parallel::test_single_group",
            "test_phase_12_9_gb.py::TestV5Parallel::test_insufficient_data_groups",
            "test_phase_12_9_gb.py::TestV5Parallel::test_scaling_diagnostic",
        ],
        "bench_proof": [],
        "impl_tag": "NUMBA",
    },
    "V5.threading_env": {
        "name": "V5 threading environment",
        "description": "Threading environment restored after execution",
        "module": "groupby_regression_optimized",
        "proof": ["test_phase_12_9_gb.py::TestV5Parallel::test_threading_env_restored"],
        "bench_proof": [],
        "impl_tag": None,
    },

    # ====== SW — Sliding Window (v4-aligned API) ======
    "SW.basic": {
        "name": "Sliding window basic 3D",
        "description": "Basic sliding window on 3-dimensional bins (v4-aligned: gb_columns, linear_columns)",
        "module": "groupby_regression_sliding_window",
        "proof": ["test_groupby_regression_sliding_window.py::test_sliding_window_basic_3d_verbose"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "SW.aggregation": {
        "name": "Sliding window aggregation",
        "description": "Aggregation functions in window",
        "module": "groupby_regression_sliding_window",
        "proof": ["test_groupby_regression_sliding_window.py::test_sliding_window_aggregation_verbose"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "SW.linear_fit": {
        "name": "Sliding window linear fit",
        "description": "Linear regression within sliding window (V1 numpy lstsq / V2 Numba)",
        "module": "groupby_regression_sliding_window",
        "proof": ["test_groupby_regression_sliding_window.py::test_sliding_window_linear_fit_recover_slope"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "SW.empty_window": {
        "name": "Empty window handling",
        "description": "Windows with no data handled gracefully",
        "module": "groupby_regression_sliding_window",
        "proof": ["test_groupby_regression_sliding_window.py::test_empty_window_handling_no_crash"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "SW.min_stat": {
        "name": "Minimum entries enforcement",
        "description": "Windows below min_stat flagged or dropped (renamed from min_entries)",
        "module": "groupby_regression_sliding_window",
        "proof": ["test_groupby_regression_sliding_window.py::test_min_entries_enforcement_flag_or_drop"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "SW.validation": {
        "name": "Sliding window input validation",
        "description": "Invalid window specs, missing columns, bad types rejected",
        "module": "groupby_regression_sliding_window",
        "proof": [
            "test_groupby_regression_sliding_window.py::test_invalid_window_spec_rejected",
            "test_groupby_regression_sliding_window.py::test_missing_columns_raise_valueerror",
            "test_groupby_regression_sliding_window.py::test_float_bins_rejected_in_m71",
            "test_groupby_regression_sliding_window.py::test_min_entries_must_be_positive_int",
            "test_groupby_regression_sliding_window.py::test_selection_mask_length_and_dtype",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "SW.backend_auto": {
        "name": "Backend auto-dispatch",
        "description": "backend='auto' detects Numba availability, dispatches V2 (numba) or V1 (numpy)",
        "module": "groupby_regression_sliding_window",
        "proof": [
            "test_invariance_sliding_window.py::TestSWNumba::test_sw_numba_backend_used",
            "test_invariance_sliding_window.py::TestSWNumba::test_sw_numba_equals_numpy",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "SW.boundary": {
        "name": "Boundary truncation",
        "description": "Boundary bins truncated at edges",
        "module": "groupby_regression_sliding_window",
        "proof": [
            "test_groupby_regression_sliding_window.py::test_single_bin_dataset_ok",
            "test_groupby_regression_sliding_window.py::test_all_bins_below_threshold",
            "test_groupby_regression_sliding_window.py::test_boundary_bins_truncation_counts",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "SW.multi_target": {
        "name": "Sliding window multi-target",
        "description": "Multiple fit targets in sliding window",
        "module": "groupby_regression_sliding_window",
        "proof": ["test_groupby_regression_sliding_window.py::test_multi_target_fit_output_schema"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "SW.multi_predictor": {
        "name": "Sliding window multi-predictor",
        "description": "Multiple linear predictors (e.g. x + x²) in sliding window",
        "module": "groupby_regression_sliding_window",
        "proof": [
            "test_groupby_regression_sliding_window.py::test_statsmodels_formula_rich_syntax_relaxed",
            "test_invariance_sliding_window.py::TestSWMultiPredictor::test_sw_multi_predictor_nsigma_recovery",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "SW.weighted": {
        "name": "Sliding window weighted fits (WLS)",
        "description": "Weighted least squares in sliding window — planned for V3/V4",
        "module": "groupby_regression_sliding_window",
        "proof": [],
        "bench_proof": [],
        "impl_tag": "PLANNED",
    },
    "SW.selection": {
        "name": "Sliding window selection mask",
        "description": "Selection mask filters rows before windowing",
        "module": "groupby_regression_sliding_window",
        "proof": ["test_groupby_regression_sliding_window.py::test_selection_mask_filters_pre_windowing"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "SW.metadata": {
        "name": "Sliding window metadata",
        "description": "Metadata in DataFrame.attrs (window_spec, backend_used, algorithm, suffix)",
        "module": "groupby_regression_sliding_window",
        "proof": ["test_groupby_regression_sliding_window.py::test_metadata_presence_in_attrs"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "SW.suffix": {
        "name": "Sliding window output suffix",
        "description": "Configurable suffix for output columns (default '_sw', v4-aligned)",
        "module": "groupby_regression_sliding_window",
        "proof": [
            "test_groupby_regression_sliding_window.py::test_sliding_window_basic_3d_verbose",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "SW.return_metadata": {
        "name": "Sliding window return_metadata",
        "description": "return_metadata=True returns (DataFrame, dict) with computation details",
        "module": "groupby_regression_sliding_window",
        "proof": [
            "test_groupby_regression_sliding_window.py::test_metadata_presence_in_attrs",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "SW.omitted_dims": {
        "name": "Omitted window dims default to 0",
        "description": "window_spec with missing gb_columns dimensions defaults to 0 (no sliding)",
        "module": "groupby_regression_sliding_window",
        "proof": [
            "test_groupby_regression_sliding_window.py::test_invalid_window_spec_rejected",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "SW.v4_parity": {
        "name": "SW window-zero parity with V4",
        "description": "Zero window size reproduces V4 standard groupby",
        "module": "groupby_regression_sliding_window",
        "proof": [
            "test_groupby_regression_sliding_window.py::test_window_size_zero_parity_with_v4_relaxed",
            "test_invariance_sliding_window.py::TestSWOracleParity::test_sw_window0_equals_per_bin_ols",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "SW.bin_helpers": {
        "name": "Internal bin helpers",
        "description": "bin_index_map and offset/neighbor generation",
        "module": "groupby_regression_sliding_window",
        "proof": [
            "test_groupby_regression_sliding_window.py::test__build_bin_index_map_contract",
            "test_groupby_regression_sliding_window.py::test__generate_offsets_and_get_neighbors_truncate_contract",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "SW.smoke_gate": {
        "name": "Realistic smoke normalised residuals",
        "description": "End-to-end scenario with normalised residuals",
        "module": "groupby_regression_sliding_window",
        "proof": ["test_groupby_regression_sliding_window.py::test_realistic_smoke_normalised_residuals_gate"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "SW.invariance": {
        "name": "Sliding window invariance tests",
        "description": "Statistical validation: nsigma recovery, error estimator consistency, pull distributions",
        "module": "groupby_regression_sliding_window",
        "proof": [
            "test_invariance_sliding_window.py::TestSWValueRecovery::test_sw_slope_nsigma_recovery",
            "test_invariance_sliding_window.py::TestSWErrorEstimator::test_sw_error_estimator_consistency",
            "test_invariance_sliding_window.py::TestSWPullDistribution::test_sw_pull_distribution",
            "test_invariance_sliding_window.py::TestSWStructuralInvariants::test_sw_window0_entries_equals_bin",
            "test_invariance_sliding_window.py::TestSWStructuralInvariants::test_sw_window0_neighbors_equals_one",
            "test_invariance_sliding_window.py::TestSWStructuralInvariants::test_sw_interior_entries_27x",
            "test_invariance_sliding_window.py::TestSWMetamorphic::test_sw_permutation_invariance",
            "test_invariance_sliding_window.py::TestSWMetamorphic::test_sw_determinism",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "SW.parallel": {
        "name": "Parallel sliding window (split-column)",
        "description": "Multi-sector parallel execution via ProcessPoolExecutor with fork() COW, "
                       "O(N) counting sort, zero-pickle dispatch (~200B/task vs 125MB)",
        "module": "groupby_regression_sliding_window",
        "proof": [
            "test_parallel_sliding_window.py::TestParallelCorrectness::test_parallel_matches_serial",
            "test_parallel_sliding_window.py::TestParallelCorrectness::test_parallel_single_worker",
            "test_parallel_sliding_window.py::TestParallelCorrectness::test_parallel_multiple_targets",
            "test_parallel_sliding_window.py::TestParallelCorrectness::test_parallel_output_columns",
            "test_parallel_sliding_window.py::TestParallelPerformance::test_parallel_speedup",
            "test_parallel_sliding_window.py::TestParallelErrorHandling::test_on_error_nan_fills",
            "test_parallel_sliding_window.py::TestParallelErrorHandling::test_on_error_raise_raises",
            "test_parallel_sliding_window.py::TestParallelEdgeCases::test_empty_dataframe",
        ],
        "bench_proof": [
            "bench_slidingwindow_parallel.py::parallel_scaling (1-36 workers) [GATED]",
            "bench_slidingwindow_parallel.py::serial_vs_parallel_validation [GATED]",
            "bench_slidingwindow_parallel.py::counting_sort_vs_argsort [MONITOR]",
        ],
        "impl_tag": "NUMBA",
    },
    "SW.v5_dominance": {
        "name": "V5 algorithm dominance across all backends",
        "description": "V5 (incremental+numba) is 25-68x faster than V1/V2/V3 across all tested "
                       "configurations. Validated via parametric benchmark with cost model fitting.",
        "module": "groupby_regression_sliding_window",
        "proof": [
            "test_invariance_sliding_window.py::TestSWNumba::test_sw_numba_equals_numpy",
            "test_parallel_sliding_window.py::TestParallelCorrectness::test_parallel_matches_serial",
        ],
        "bench_proof": [
            "bench_slidingwindow_parametric.py::V1_vs_V2_vs_V3_vs_V5_validation (30/30 PASS) [GATED]",
            "bench_slidingwindow_parametric.py::algorithm_recommendation (V5 wins 10/10) [MONITOR]",
            "bench_slidingwindow_parametric.py::cost_model_fit (11 models, R2>0.99) [MONITOR]",
        ],
        "impl_tag": "NUMBA",
    },

    # ====== META — Fit metadata ======
    "META.column_validation": {
        "name": "Column name validation",
        "description": "Validates column names against naming rules",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_fit_metadata.py::TestColumnNameValidation::test_valid_simple_names",
            "test_fit_metadata.py::TestColumnNameValidation::test_valid_with_underscores",
            "test_fit_metadata.py::TestColumnNameValidation::test_valid_with_numbers",
            "test_fit_metadata.py::TestColumnNameValidation::test_valid_starting_with_underscore",
            "test_fit_metadata.py::TestColumnNameValidation::test_valid_mixed_case",
            "test_fit_metadata.py::TestColumnNameValidation::test_valid_physics_names",
            "test_fit_metadata.py::TestColumnNameValidation::test_invalid_starts_with_number",
            "test_fit_metadata.py::TestColumnNameValidation::test_invalid_hyphen",
            "test_fit_metadata.py::TestColumnNameValidation::test_invalid_space",
            "test_fit_metadata.py::TestColumnNameValidation::test_invalid_special_chars",
            "test_fit_metadata.py::TestColumnNameValidation::test_invalid_brackets",
            "test_fit_metadata.py::TestColumnNameValidation::test_context_in_error_message",
            "test_fit_metadata.py::TestColumnNameValidation::test_empty_list_valid",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "META.prediction_formula": {
        "name": "Prediction formula generation",
        "description": "Generates symbolic prediction formulas",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_fit_metadata.py::TestFormulaGeneration::test_single_predictor_with_intercept",
            "test_fit_metadata.py::TestFormulaGeneration::test_single_predictor_without_intercept",
            "test_fit_metadata.py::TestFormulaGeneration::test_two_predictors_with_intercept",
            "test_fit_metadata.py::TestFormulaGeneration::test_two_predictors_without_intercept",
            "test_fit_metadata.py::TestFormulaGeneration::test_many_predictors",
            "test_fit_metadata.py::TestFormulaGeneration::test_preserves_predictor_order",
            "test_fit_metadata.py::TestFormulaGeneration::test_empty_predictors_with_intercept",
            "test_fit_metadata.py::TestFormulaGeneration::test_empty_predictors_without_intercept_raises",
            "test_fit_metadata.py::TestFormulaGeneration::test_different_suffixes",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "META.residual_formula": {
        "name": "Residual formula generation",
        "description": "Generates residual = target - prediction formulas",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_fit_metadata.py::TestDerivedColumnFormulas::test_simple_residual",
            "test_fit_metadata.py::TestDerivedColumnFormulas::test_parentheses_around_prediction",
            "test_fit_metadata.py::TestDerivedColumnFormulas::test_complex_prediction",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "META.pull_formula": {
        "name": "Pull formula generation",
        "description": "Generates pull = residual / quality formulas",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_fit_metadata.py::TestDerivedColumnFormulas::test_simple_pull",
            "test_fit_metadata.py::TestDerivedColumnFormulas::test_parentheses_around_residual",
            "test_fit_metadata.py::TestDerivedColumnFormulas::test_mad_based_pull",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "META.schema": {
        "name": "Metadata schema",
        "description": "Complete metadata schema with version, columns, parameters",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_fit_metadata.py::TestMetadataSchema::test_schema_version_present",
            "test_fit_metadata.py::TestMetadataSchema::test_all_top_level_keys_present",
            "test_fit_metadata.py::TestMetadataSchema::test_columns_subsections_present",
            "test_fit_metadata.py::TestMetadataSchema::test_parameters_complete",
            "test_fit_metadata.py::TestMetadataSchema::test_single_target_formulas",
            "test_fit_metadata.py::TestMetadataSchema::test_multiple_targets",
            "test_fit_metadata.py::TestMetadataSchema::test_fit_intercept_true_includes_intercept",
            "test_fit_metadata.py::TestMetadataSchema::test_fit_intercept_false_excludes_intercept",
            "test_fit_metadata.py::TestMetadataSchema::test_columns_categorization",
            "test_fit_metadata.py::TestMetadataSchema::test_diagnostics_empty_when_diag_false",
            "test_fit_metadata.py::TestMetadataSchema::test_diagnostics_populated_when_diag_true",
            "test_fit_metadata.py::TestMetadataSchema::test_custom_diag_prefix",
            "test_fit_metadata.py::TestMetadataSchema::test_medians_empty_when_not_provided",
            "test_fit_metadata.py::TestMetadataSchema::test_medians_populated_when_provided",
            "test_fit_metadata.py::TestMetadataSchema::test_invalid_fit_column_raises",
            "test_fit_metadata.py::TestMetadataSchema::test_invalid_linear_column_raises",
            "test_fit_metadata.py::TestMetadataIntegration::test_pull_both_rms_and_mad",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "META.consistency": {
        "name": "Metadata consistency",
        "description": "Formula columns match coefficient lists",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_fit_metadata.py::TestMetadataIntegration::test_formula_columns_match_coefficient_list",
            "test_fit_metadata.py::TestMetadataIntegration::test_residual_references_original_target",
            "test_fit_metadata.py::TestMetadataIntegration::test_pull_references_quality_column",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "META.edge_cases": {
        "name": "Metadata edge cases",
        "description": "Empty suffix, long suffix, many groups, single-char",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_fit_metadata.py::TestMetadataIntegration::test_empty_suffix",
            "test_fit_metadata.py::TestMetadataIntegration::test_long_suffix",
            "test_fit_metadata.py::TestMetadataIntegration::test_many_group_columns",
            "test_fit_metadata.py::TestMetadataIntegration::test_single_character_names",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "META.formula_eval": {
        "name": "Formula evaluation",
        "description": "Generated formulas evaluate on real DataFrames",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_fit_metadata.py::TestFormulaEvaluation::test_prediction_formula_evaluates",
            "test_fit_metadata.py::TestFormulaEvaluation::test_residual_formula_evaluates",
            "test_fit_metadata.py::TestFormulaEvaluation::test_pull_rms_formula_evaluates",
            "test_fit_metadata.py::TestFormulaEvaluation::test_pull_mad_formula_evaluates",
            "test_fit_metadata.py::TestFormulaEvaluation::test_no_intercept_formula_evaluates",
            "test_fit_metadata.py::TestFormulaEvaluation::test_multiple_targets_all_evaluate",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "META.column_selection": {
        "name": "V4 column selection optimization",
        "description": "V4 selects minimal columns for memory",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_fit_metadata.py::TestV4ColumnSelection::test_v4_column_selection_basic",
            "test_fit_metadata.py::TestV4ColumnSelection::test_v3_column_selection_basic",
            "test_fit_metadata.py::TestV4ColumnSelection::test_v4_includes_weights",
            "test_fit_metadata.py::TestV4ColumnSelection::test_v4_includes_median_columns",
            "test_fit_metadata.py::TestV4ColumnSelection::test_v4_deterministic_column_order",
            "test_fit_metadata.py::TestV4ColumnSelection::test_v4_fit_results_unchanged",
            "test_fit_metadata.py::TestV4ColumnSelection::test_v4_missing_median_column_raises",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },

    # ====== STD — Standardization ======
    "STD.column_consistency": {
        "name": "V2/V3/V4 column consistency",
        "description": "All versions produce consistent output columns",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_groupby_regression_standardization.py::test_v2_v3_v4_columns_without_diag",
            "test_groupby_regression_standardization.py::test_v2_v3_v4_columns_with_diag",
        ],
        "bench_proof": [],
        "impl_tag": None,
    },
    "STD.suffix": {
        "name": "Suffix application",
        "description": "Custom suffix applied to all output columns",
        "module": "groupby_regression_optimized",
        "proof": ["test_groupby_regression_standardization.py::test_suffix_applied_to_all_output_columns"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "STD.rms_mad": {
        "name": "RMS/MAD always present",
        "description": "RMS and MAD columns always present",
        "module": "groupby_regression_optimized",
        "proof": ["test_groupby_regression_standardization.py::test_rms_mad_always_present"],
        "bench_proof": [],
        "impl_tag": None,
    },
    "STD.merge_fits": {
        "name": "Multiple fits merge with suffix",
        "description": "Multiple fit results merge with distinct suffixes",
        "module": "groupby_regression_optimized",
        "proof": ["test_groupby_regression_standardization.py::test_merge_multiple_fits_with_suffix"],
        "bench_proof": [],
        "impl_tag": None,
    },

    # ====== PYARROW ======
    "PYARROW.backend_selection": {
        "name": "PyArrow backend selection",
        "description": "Backend auto-selection and explicit override",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_pyarrow_backend.py::TestPyArrowBackend::test_backend_pandas_explicit",
            "test_pyarrow_backend.py::TestPyArrowBackend::test_backend_pyarrow_explicit",
            "test_pyarrow_backend.py::TestPyArrowBackend::test_backend_auto_below_threshold",
            "test_pyarrow_backend.py::TestPyArrowBackend::test_backend_auto_above_threshold",
            "test_pyarrow_backend.py::TestPyArrowBackend::test_backend_invalid_raises",
        ],
        "bench_proof": [],
        "impl_tag": "PYARROW",
    },
    "PYARROW.parity": {
        "name": "Pandas/PyArrow numerical parity",
        "description": "PyArrow produces identical results to pandas",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_pyarrow_backend.py::TestPyArrowParity::test_results_match_simple",
            "test_pyarrow_backend.py::TestPyArrowParity::test_results_match_multicolumn_groupby",
            "test_pyarrow_backend.py::TestPyArrowParity::test_results_match_with_weights",
            "test_pyarrow_backend.py::TestPyArrowParity::test_results_match_multiple_targets",
            "test_pyarrow_backend.py::TestPyArrowParity::test_results_match_no_intercept",
        ],
        "bench_proof": [],
        "impl_tag": "PYARROW",
    },
    "PYARROW.sort_stability": {
        "name": "PyArrow sort stability",
        "description": "Sort order and determinism matches pandas",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_pyarrow_backend.py::TestPyArrowParity::test_sort_stability_matches_pandas",
            "test_pyarrow_backend.py::TestPyArrowParity::test_deterministic_column_order",
            "test_pyarrow_backend.py::TestPyArrowParity::test_deterministic_results_across_runs",
            "test_pyarrow_backend.py::TestPyArrowParity::test_row_order_within_groups_matches_pandas",
        ],
        "bench_proof": [],
        "impl_tag": "PYARROW",
    },
    "PYARROW.memory": {
        "name": "PyArrow memory behavior",
        "description": "Arrow pool monitoring, memory reduction",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_pyarrow_backend.py::TestPyArrowEdgeCases::test_arrow_pool_bytes_check",
            "test_pyarrow_backend.py::TestPyArrowEdgeCases::test_pyarrow_backend_functional",
            "test_pyarrow_backend.py::TestPyArrowEdgeCases::test_memory_reduction_large_dataset",
        ],
        "bench_proof": [],
        "impl_tag": "PYARROW",
    },
    "PYARROW.edge_cases": {
        "name": "PyArrow edge cases",
        "description": "Empty, single group/row, NaN, selection",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_pyarrow_backend.py::TestPyArrowEdgeCases::test_empty_dataframe",
            "test_pyarrow_backend.py::TestPyArrowEdgeCases::test_single_group",
            "test_pyarrow_backend.py::TestPyArrowEdgeCases::test_single_row",
            "test_pyarrow_backend.py::TestPyArrowEdgeCases::test_with_nan_values",
            "test_pyarrow_backend.py::TestPyArrowEdgeCases::test_with_selection",
        ],
        "bench_proof": [],
        "impl_tag": "PYARROW",
    },
    "PYARROW.metadata": {
        "name": "PyArrow metadata export",
        "description": "Metadata export works with PyArrow backend",
        "module": "groupby_regression_optimized",
        "proof": [
            "test_pyarrow_backend.py::TestPyArrowMetadata::test_metadata_export_pyarrow",
            "test_pyarrow_backend.py::TestPyArrowMetadata::test_metadata_matches_pandas",
        ],
        "bench_proof": [],
        "impl_tag": "PYARROW",
    },

    # ====== XVAL — Cross-validation ======
    "XVAL.robust_v4_parity": {
        "name": "Robust vs V4 numerical parity",
        "description": "Robust and V4 produce consistent results",
        "module": "groupby_regression",
        "proof": [
            "test_cross_validation.py::test_robust_vs_v4_numerical_parity",
            "test_cross_validation.py::test_robust_vs_v4_agreement_on_common_groups",
        ],
        "bench_proof": ["bench_comparison.py::compute_agreement() [MONITOR]"],
        "impl_tag": None,
    },
    "XVAL.robust_v2": {
        "name": "Robust vs V2 structural agreement",
        "description": "Robust and V2 produce consistent structural output",
        "module": "groupby_regression",
        "proof": ["test_cross_validation.py::test_robust_vs_v2_structural_agreement"],
        "bench_proof": [],
        "impl_tag": None,
    },

    # ====== TPC ======
    "TPC.distortion_recovery": {
        "name": "TPC distortion recovery pipeline",
        "description": "End-to-end TPC distortion correction validation",
        "module": "synthetic_tpc_distortion",
        "proof": ["test_tpc_distortion_recovery.py::test_tpc_distortion_recovery"],
        "bench_proof": [],
        "impl_tag": None,
    },
}
# fmt: on

IMPL_TAGS = {
    "NUMBA": "Requires Numba JIT compilation",
    "STATSMODELS": "Requires statsmodels library",
    "PYARROW": "Requires PyArrow library",
    "SKLEARN": "Requires scikit-learn library",
    "PARALLEL": "Uses joblib parallelization",
    "STREAMING": "Streaming/chunked processing",
    "EXPERIMENTAL": "Experimental / not yet stable",
}

VERBOSE_DUPLICATES = {
    "test_groupby_regression_sliding_window_verbose.py": "test_groupby_regression_sliding_window.py",
}

def get_feature_count():
    return len(FEATURE_TAXONOMY)

def get_all_proof_tests():
    tests = set()
    for feat in FEATURE_TAXONOMY.values():
        tests.update(feat["proof"])
    return tests

if __name__ == "__main__":
    print(f"Feature count: {get_feature_count()}")
    modules = {}
    for feat in FEATURE_TAXONOMY.values():
        m = feat["module"]
        modules[m] = modules.get(m, 0) + 1
    for m, c in sorted(modules.items()):
        print(f"  {m}: {c} features")
    tags = {}
    for feat in FEATURE_TAXONOMY.values():
        t = feat.get("impl_tag") or "none"
        tags[t] = tags.get(t, 0) + 1
    print()
    for t, c in sorted(tags.items()):
        print(f"  impl_tag={t}: {c}")
    all_proofs = get_all_proof_tests()
    print(f"\nTotal unique proof tests: {len(all_proofs)}")
    bench = sum(1 for f in FEATURE_TAXONOMY.values() if f["bench_proof"])
    print(f"Features with bench_proof: {bench}")
