#!/usr/bin/env python3
"""
Example 05: Export to C++ Macro

Demonstrates:
- Exporting DSL definitions to .C macro file
- Generated test harness
- Sharing analysis code with C++ users
"""

import sys
import os
# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import ROOT
from RDataFrameDSL import DSLCompiler

print("=" * 60)
print("Example 05: Export to C++ Macro")
print("=" * 60)

# =============================================================================
# Create DSLCompiler with Physics Analysis
# =============================================================================

print("\nCreating DSLCompiler...")

schema = {
    "px": "double",
    "py": "double",
    "pz": "double",
    "tracks": "RVec<TLorentzVector>",
}

dsl = DSLCompiler(schema)

print("Defining expressions...")

# Scalar calculations
dsl.define("pt", "sqrt(px**2 + py**2)")
dsl.define("p", "sqrt(px**2 + py**2 + pz**2)")

# Track operations
dsl.define("n_tracks", "tracks.size()")
dsl.define("track_pts", "tracks.Pt()")
dsl.define("lead3_pt", "tracks[:3].Pt()")

print("\nDefined expressions:")
for name in ["pt", "p", "n_tracks", "track_pts", "lead3_pt"]:
    print(f"  {name}")

# =============================================================================
# Preview C++ Code
# =============================================================================

print("\n" + "=" * 60)
print("Generated C++ (preview):")
print("=" * 60)
cpp_code = dsl.preview()
print(cpp_code)

# =============================================================================
# Export to Macro File (Manual approach - more robust)
# =============================================================================

macro_path = "analysis_functions.C"

print("=" * 60)
print(f"Exporting to: {macro_path}")
print("=" * 60)

# Check if export_macro method exists
if hasattr(dsl, 'export_macro'):
    print("\nUsing export_macro() method...")
    try:
        dsl.export_macro(macro_path, include_test=True)
        print(f"  Exported successfully!")
    except Exception as e:
        print(f"  export_macro failed: {e}")
        print("  Falling back to manual export...")
        # Manual export fallback
        with open(macro_path, 'w') as f:
            f.write("// RDataFrameDSL Generated Macro\n")
            f.write("// Generated by example 05\n\n")
            f.write("#include <cmath>\n")
            f.write("#include <ROOT/RVec.hxx>\n")
            f.write("#include <TLorentzVector.h>\n\n")
            f.write(cpp_code)
        print(f"  Manually exported to {macro_path}")
else:
    print("\nNote: export_macro() not available, using manual export...")
    # Manual export
    with open(macro_path, 'w') as f:
        f.write("// RDataFrameDSL Generated Macro\n")
        f.write("// Generated by example 05\n\n")
        f.write("#include <cmath>\n")
        f.write("#include <ROOT/RVec.hxx>\n")
        f.write("#include <TLorentzVector.h>\n\n")
        f.write(cpp_code)
    print(f"  Manually exported to {macro_path}")

# Show the generated file
if os.path.exists(macro_path):
    print(f"\nGenerated macro file ({macro_path}):")
    print("-" * 60)
    
    with open(macro_path, 'r') as f:
        content = f.read()
        # Show first 50 lines
        lines = content.split('\n')
        for i, line in enumerate(lines[:50]):
            print(line)
        if len(lines) > 50:
            print(f"\n... ({len(lines) - 50} more lines)")

# =============================================================================
# Using the Macro in ROOT
# =============================================================================

print("\n" + "=" * 60)
print("Using the Macro:")
print("=" * 60)

print("""
Option 1: Load in Python
  ROOT.gInterpreter.ProcessLine('.L analysis_functions.C')

Option 2: Load in ROOT prompt  
  root [0] .L analysis_functions.C
  root [1] auto rdf = ROOT::RDataFrame("Events", "data.root");
  root [2] auto rdf2 = rdf.Define("pt", "alias_pt(px, py)");

Option 3: Compile as shared library
  root [0] .L analysis_functions.C+
""")

# =============================================================================
# Test the Exported Functions
# =============================================================================

print("=" * 60)
print("Testing Exported Functions:")
print("=" * 60)

try:
    # Load the macro
    print("\n  Loading macro...")
    ROOT.gInterpreter.ProcessLine(f'.L {macro_path}')
    
    # Find the actual function name (includes UUID suffix)
    pt_func_name = None
    for name in dir(ROOT):
        if name.startswith('alias_pt_'):
            pt_func_name = name
            break
    
    if pt_func_name:
        func = getattr(ROOT, pt_func_name)
        result = func(3.0, 4.0)
        print(f"\n  {pt_func_name}(3.0, 4.0) = {result}")
        print(f"  Expected: 5.0 {'✓' if abs(result - 5.0) < 0.001 else 'MISMATCH!'}")
    else:
        print("\n  Note: Could not find alias_pt function (may have different name)")
    
    print("\n  Macro loaded successfully!")
    
except Exception as e:
    print(f"\n  Could not test: {e}")

# =============================================================================
# Summary
# =============================================================================

print("\n" + "=" * 60)
print("Summary:")
print("=" * 60)
print(f"  Generated: {macro_path}")
print(f"  Contains: {len(dsl._functions)} DSL functions as C++ code")
print(f"\nYou can share this file with C++ users who don't use Python!")

print("\n" + "=" * 60)
print("Done!")
print("=" * 60)
